# https://docs.gitlab.com/ee/ci/yaml/
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# https://docs.gitlab.com/ee/ci/migration/github_actions.html

stages:
  - build

构建Docker镜像:
  # Use the official docker image.
  tags:
    #- txy
    #- oracle-amd64-1
    - oracle-arm64
  image: docker:dind
  #image: docker:latest
  #image: docker:cli
  #services:
  #  - docker:dind
  stage: build
  variables:
    DOCKER_HUB_IMAGE_NAME: $DOCKER_HUB_USER/$CI_PROJECT_NAME
    DOCKER_IMAGE_NAME: $DOCKER_REGISTRY/$CI_PROJECT_NAME
    DOCKER_USER: "nili"
  before_script:
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create --use --name mybuilder
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY_URL
    - TIME=$(TZ='UTC-8' date +'%Y-%m-%d-%H-%M-%S')
    #- docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - docker buildx build --file Dockerfile --progress=plain --tag "$DOCKER_IMAGE_NAME:latest" --tag "$DOCKER_IMAGE_NAME:$TIME" --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7 --push .
    #linux/amd64,linux/arm64,linux/386,linux/arm/v7
    #- docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_PASSWORD"
    #- docker tag "$DOCKER_IMAGE_NAME:latest" "$DOCKER_HUB_IMAGE_NAME:latest"
    #- docker tag "$DOCKER_IMAGE_NAME:latest" "$DOCKER_HUB_IMAGE_NAME:$TIME"
    #- docker push "$DOCKER_HUB_IMAGE_NAME:latest" "$DOCKER_HUB_IMAGE_NAME:$TIME"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

