name: 自动构建docker镜像

on:
  schedule:
    - cron: "36 19 * * 0"
  #watch:
  #  types: started
  workflow_dispatch:

#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4

#      - name: Login to GHCR
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Respository Name
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> "$GITHUB_ENV"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          #  ghcr.io/username/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            {{date 'YYYY/MM/DD/hh/mm/ss'}}
#            type=schedule,pattern={{date 'YYYY/MM/DD'}}
#            type=semver,pattern={{version}}
#            type=semver,pattern=$()
#            type=ref,event=branch
#            type=sha
#            type=ref,event=pr
#            type=semver,pattern={{major}}.{{minor}}
#            type=semver,pattern={{major}}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push all
        id: docker_build_all
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: all Image digest
        run: echo ${{ steps.docker_build_all.outputs.digest }}
